export const textoRetos = [
  'Beber 1 shot o llamar a tu ex',
  'Beber un vaso de cerveza sin usar tus manos o decir un secreto vergonzoso',
  'Hacer un brindis creativo o tomarte 2 shots seguidos',
  'Beber directamente de una botella o hacer una broma a un amigo',
  'Tomar un trago en menos de 5 segundos o hacer una rutina de baile improvisada',
  'Hacer un brindis en un idioma extranjero o beber agua con gas',
  'Bailar con un objeto inanimado o beber dos vasos de agua',
  'Decir un trabalenguas sin equivocarte o tomarte un chupito de vinagre',
  'Abraza a alguien sin camisa/blusa o toma 3 shots',
  'Di quién te gusta del grupo o toma 2 shots',
  'Todos tomen un shot',
  'Muestra un video para adultos que quisieras recrear con alguien del grupo o compra una sellada',
  'Dale un pico a alguien durante 10 segundos o toma un shot',
  'Cuenta tu peor cita o toma un shot',
  'Llévate a alguien al baño o toma 2 shot',
  'Si tienes pareja bésense románticamente después de cada ronda, si se les olvida cada uno se toma un shot por ronda',
  'Di la parte más atractiva del cuerpo del sexo opuesto o toma un shot',
  'Menciona con quién del grupo grabarías un video para adultos o toma dos shots',
  'Di: El que se mueva es gay, el primero que se mueve toma un shot',
  'Ponte una venda y deja que alguien te bese o toma 2 shots',
  'Muestra una fotografía en la que creas que te ves muy sexy o toma un shot',
  'Siéntate al lado de quién te guste o toma un shot',
  'Di la canción que pones cuando estás con alguien en la cama o toma un shot',
  'Si tienes tatuajes muéstralos todos, si no tienes toma un shot',
  'Susurra algo en la oreja de la persona a tu derecha, si se ríe se toma un shot, si no te la tomas tú',
  'Desabrocha el brasier a una chica con una mano, si no lo logras te tomas 2 shots por monse',
  'Tomate un shot sin usar las manos',
  'Dale un pico a alguien de tu mismo sexo o tomas 2 shots',
  'El más ebrio del grupo baila una canción',
  'Has 30 flexiones o 30 sentadillas, si no lo logras toma 2 shots',
  'Ponme una venda y deja que la persona que te gusta te haga lo que le nazca o ambos se toman un shot',
  'Comparte un shot con tu mejor amigo/a',
  'Quítate una prenda o toma un shot',
  'Deja que todos te sirvan algo en tu shot y te lo tomas',
  'Verdad o reto todos',
  'El o la más sano del grupo toma 2 shots para igualarse',
  'Toma un shot mientras te paras en una pierna',
  'Todos toman un shot',
  'Toma la mitad de shots del número de parejas sexuales que has tenido, si no te creen tomas el doble',
  'Has fuercitas/vencidas con alguien del grupo, el perdedor se toma un shot',
  'El pisado del grupo se toma 3 shots',
  'Llama a tu ex y dile para irse a un hotel o toma 2 shots',
  'Todos pongan cuota para comprar otra botella, el que pone menos o no pone toma 3 shots',
  'Las chicas del grupo deben tomar un shot',
  'El más bajito de los hombres toma un shot a ver si así crece',
  'La chica más alta toma un shot a ver si así se le sube',
  'Que las chicas boten, el más guapo del grupo se toma 2 shots',
];
export const textoRetosTodos = [
  'Todos tomen un shot',
  'Si tienes pareja bésense románticamente después de cada ronda, si se les olvida cada uno se toma un shot por ronda',
  'Si tienes tatuajes muéstralos todos, si no tienes toma un shot',
  'El más ebrio del grupo baila una canción',
  'Verdad o reto todos',
  'El o la más sano del grupo toma 2 shots para igualarse',
  'Todos toman un shot',
  'El pisado del grupo se toma 3 shots',
  'Todos pongan cuota para comprar otra botella, el que pone menos o no pone toma 3 shots',
  'Las chicas del grupo deben tomar un shot',
  'El más bajito de los hombres toma un shot a ver si así crece',
  'La chica más alta toma un shot a ver si así se le sube',
  'Que las chicas boten, el más guapo del grupo se toma 2 shots',
];
